#!/bin/bash
cd $OPENSHIFT_DATA_DIR

if [ ! -d apache-maven-3.3.9 ]; then
  wget http://www.eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  tar -zxf apache-maven-3.3.9-bin.tar.gz
fi